name: chichefl
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.9.30=h06a4308_1
  - certifi=2021.10.8=py39h06a4308_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.4.3=py39h06a4308_0
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy-base=1.20.3=py39h74d4b33_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - pcre=8.45=h295c915_0
  - pip=21.2.4=py37h06a4308_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.9.1=py3.9_cuda11.1_cudnn8.0.5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - scipy=1.7.1=py39h292c36d_2
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.9.1=py39
  - torchvision=0.10.1=py39_cu111
  - tornado=6.1=py39h27cfd23_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.14.0
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - attrs==21.2.0
    - blessings==1.7
    - cachetools==4.2.4
    - chardet==4.0.0
    - charset-normalizer==2.0.6
    - click==8.0.1
    - colorful==0.5.4
    - filelock==3.2.0
    - google-api-core==1.31.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.41.0
    - hiredis==2.0.0
    - idna==3.2
    - jsonschema==4.0.1
    - markdown==3.3.4
    - msgpack==1.0.2
    - multidict==5.1.0
    - numpy==1.21.2
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.1
    - opencensus==0.7.13
    - opencensus-context==0.1.2
    - packaging==21.0
    - pillow==8.3.2
    - prometheus-client==0.11.0
    - protobuf==3.17.3
    - psutil==5.8.0
    - py-spy==0.3.10
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyrsistent==0.18.0
    - pytz==2021.1
    - pyyaml==5.4.1
    - ray==1.6.0
    - redis==3.5.3
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.1
    - yarl==1.6.3
